# Generated by Django 5.2.7 on 2025-10-15 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='user',
            field=models.OneToOneField(help_text='User who owns this plant', on_delete=django.db.models.deletion.CASCADE, related_name='plant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantcarelog',
            name='user_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='plants.userplant'),
        ),
        migrations.AddIndex(
            model_name='plantstage',
            index=models.Index(fields=['plant_type', 'stage_order'], name='plants_plan_plant_t_890a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='plantstage',
            index=models.Index(fields=['stage_name'], name='plants_plan_stage_n_1a5fbd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantstage',
            unique_together={('plant_type', 'stage_order')},
        ),
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['user'], name='plants_user_user_id_850e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['plant_type'], name='plants_user_plant_t_858d07_idx'),
        ),
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['current_stage'], name='plants_user_current_0150ef_idx'),
        ),
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['is_healthy'], name='plants_user_is_heal_3b0519_idx'),
        ),
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['last_care_date'], name='plants_user_last_ca_cf2194_idx'),
        ),
        migrations.AddIndex(
            model_name='plantcarelog',
            index=models.Index(fields=['user_plant', 'performed_at'], name='plants_plan_user_pl_14bb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='plantcarelog',
            index=models.Index(fields=['action'], name='plants_plan_action_abb462_idx'),
        ),
    ]
