# Generated by Django 5.2.7 on 2025-10-15 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testexercise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.testexercise'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(help_text='Test this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.testexercise'),
        ),
        migrations.AddIndex(
            model_name='testexercise',
            index=models.Index(fields=['target_level_range_start'], name='tests_teste_target__485c49_idx'),
        ),
        migrations.AddIndex(
            model_name='testexercise',
            index=models.Index(fields=['test_type'], name='tests_teste_test_ty_395b75_idx'),
        ),
        migrations.AddIndex(
            model_name='testexercise',
            index=models.Index(fields=['difficulty'], name='tests_teste_difficu_32697d_idx'),
        ),
        migrations.AddIndex(
            model_name='testexercise',
            index=models.Index(fields=['is_active'], name='tests_teste_is_acti_ab8bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='tests_testa_user_id_a9b45d_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['started_at'], name='tests_testa_started_e0bee0_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['status'], name='tests_testa_status_ebfe54_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['passed'], name='tests_testa_passed_47382a_idx'),
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['test', 'question_order'], name='tests_testq_test_id_23ec7d_idx'),
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['question_type'], name='tests_testq_questio_01ca89_idx'),
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['difficulty'], name='tests_testq_difficu_3e79c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together={('test', 'question_order')},
        ),
    ]
