# Generated by Django 5.2.7 on 2025-10-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's full name", max_length=200)),
                ('father_name', models.CharField(default='Unknown', help_text="Father's name", max_length=200)),
                ('grade', models.CharField(choices=[('Nursery', 'Nursery'), ('KG-I', 'KG-I'), ('KG-II', 'KG-II'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], help_text="Student's grade", max_length=50)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', help_text="Student's shift (Morning/Afternoon)", max_length=20)),
                ('password', models.CharField(help_text="Student's password", max_length=128)),
                ('student_id', models.CharField(default='TEMP-ID', editable=False, help_text='Auto-generated student ID (C01-M-grade-section-serial)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is student active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(help_text='Campus where student is enrolled', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='campus.campus')),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Class teacher (auto-assigned from campus and grade)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
                'unique_together': {('campus', 'grade', 'shift', 'student_id')},
            },
        ),
    ]
