# Generated by Django 5.2.7 on 2025-10-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('campus', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        # Add missing fields
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=10, default='1', choices=[
                ('nursery', 'Nursery'), ('kg1', 'KG-1'), ('kg2', 'KG-2'),
                ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'),
                ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'),
                ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'),
                ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12'),
            ]),
        ),
        # First, remove the old campus field and add the new one
        migrations.RemoveField(
            model_name='student',
            name='campus',
        ),
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_teacher',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128, default='default123'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        
        # Update existing fields
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, editable=False, null=True, blank=True),
        ),
    ]
