# Generated by Django 5.2.7 on 2025-10-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', help_text="Student's shift (Morning/Afternoon)", max_length=20, null=True),
        ),
    ]
