# Generated by Django 5.2.7 on 2025-10-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('students', '0004_auto_20251017_1500'),
        ('teachers', '0006_auto_20251017_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(help_text='Campus where student is enrolled', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='campus.campus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Class teacher (auto-assigned based on grade and section)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('nursery', 'Nursery'), ('kg1', 'KG-1'), ('kg2', 'KG-2'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], default='1', help_text="Student's grade", max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is student active?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text="Student's full name", max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(help_text="Student's password", max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', help_text="Student's section", max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('campus', 'grade', 'section', 'student_id')},
        ),
    ]
