# Generated by Django 5.2.7 on 2025-10-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupjumptest',
            name='target_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_tests', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupjumptestattempt',
            name='jump_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='groups.groupjumptest'),
        ),
        migrations.AddField(
            model_name='groupjumptestattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='level',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='groups.group'),
        ),
        migrations.AddField(
            model_name='plantgrowthstage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_stages', to='groups.group'),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='groups.level'),
        ),
        migrations.AddField(
            model_name='groupjumptest',
            name='questions',
            field=models.ManyToManyField(related_name='jump_tests', to='groups.question'),
        ),
        migrations.AddField(
            model_name='userplantprogress',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plants', to='groups.group'),
        ),
        migrations.AddField(
            model_name='userplantprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('group', 'level_number')},
        ),
        migrations.AlterUniqueTogether(
            name='plantgrowthstage',
            unique_together={('group', 'stage_order')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('level', 'question_order')},
        ),
        migrations.AlterUniqueTogether(
            name='userplantprogress',
            unique_together={('user', 'group')},
        ),
    ]
