# Generated by Django 5.2.7 on 2025-10-21 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='grammar_focus',
            field=models.JSONField(blank=True, default=list, help_text='List of grammar points covered in this group'),
        ),
        migrations.AddField(
            model_name='group',
            name='oxford_word_range_end',
            field=models.PositiveIntegerField(blank=True, help_text='Ending Oxford 3000 word rank for this group', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AddField(
            model_name='group',
            name='oxford_word_range_start',
            field=models.PositiveIntegerField(blank=True, help_text='Starting Oxford 3000 word rank for this group', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AddField(
            model_name='group',
            name='topic_category',
            field=models.CharField(blank=True, help_text="Topic category (e.g., 'alphabet', 'family', 'animals', 'food')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='track',
            field=models.CharField(choices=[('beginner', 'Beginner Track (Class 3-5)'), ('intermediate', 'Intermediate Track (Class 6-10)'), ('advanced', 'Advanced Track (Fluency)')], default='beginner', help_text='Learning track this group belongs to', max_length=20),
        ),
    ]
