# Generated by Django 5.2.7 on 2025-10-15 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprogress',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupunlocktest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unlock_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupunlocktest',
            name='group',
            field=models.OneToOneField(help_text='Group this test unlocks', on_delete=django.db.models.deletion.CASCADE, related_name='unlock_test', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupunlocktestattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='groups.groupunlocktest'),
        ),
        migrations.AddField(
            model_name='groupunlocktestattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_number'], name='groups_grou_group_n_5eb4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['difficulty'], name='groups_grou_difficu_867c70_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_unlocked'], name='groups_grou_is_unlo_cd5ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_active'], name='groups_grou_is_acti_044fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupprogress',
            index=models.Index(fields=['user', 'group'], name='groups_grou_user_id_56a901_idx'),
        ),
        migrations.AddIndex(
            model_name='groupprogress',
            index=models.Index(fields=['is_completed'], name='groups_grou_is_comp_e13050_idx'),
        ),
        migrations.AddIndex(
            model_name='groupprogress',
            index=models.Index(fields=['completion_percentage'], name='groups_grou_complet_a53753_idx'),
        ),
        migrations.AddIndex(
            model_name='groupprogress',
            index=models.Index(fields=['unlocked_at'], name='groups_grou_unlocke_f09484_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupprogress',
            unique_together={('user', 'group')},
        ),
        migrations.AddIndex(
            model_name='groupunlocktest',
            index=models.Index(fields=['group'], name='groups_grou_group_i_2b0e89_idx'),
        ),
        migrations.AddIndex(
            model_name='groupunlocktest',
            index=models.Index(fields=['is_active'], name='groups_grou_is_acti_41724f_idx'),
        ),
        migrations.AddIndex(
            model_name='groupunlocktestattempt',
            index=models.Index(fields=['user', 'test'], name='groups_grou_user_id_106663_idx'),
        ),
        migrations.AddIndex(
            model_name='groupunlocktestattempt',
            index=models.Index(fields=['started_at'], name='groups_grou_started_db0332_idx'),
        ),
        migrations.AddIndex(
            model_name='groupunlocktestattempt',
            index=models.Index(fields=['passed'], name='groups_grou_passed_405054_idx'),
        ),
    ]
