# Generated by Django 5.2.7 on 2025-10-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Teacher', help_text="Teacher's full name", max_length=200)),
                ('father_name', models.CharField(default='Unknown', help_text="Father's name", max_length=200)),
                ('shift', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], default='M', help_text="Teacher's shift (Morning/Afternoon)", max_length=1)),
                ('email', models.EmailField(help_text="Teacher's email address", max_length=254, unique=True)),
                ('teacher_id', models.CharField(default='TEMP-TEACHER-ID', editable=False, help_text='Auto-generated teacher ID', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is teacher active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(help_text='Campus where teacher works', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='campus.campus')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['-created_at'],
            },
        ),
    ]
