# Generated by Django 5.2.7 on 2025-10-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='password123', help_text="Teacher's password", max_length=128),
        ),
    ]
