# Generated by Django 5.2.7 on 2025-10-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('campus', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        # Add missing fields
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, default='Unknown Teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='father_name',
            field=models.CharField(max_length=200, default='Unknown'),
        ),
        # Handle existing assigned_classroom field
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_classroom',
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_class',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classroom'),
        ),
        # Handle existing current_campus field
        migrations.RemoveField(
            model_name='teacher',
            name='current_campus',
        ),
        migrations.AddField(
            model_name='teacher',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=20, unique=True, editable=False, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
