# Generated by Django 5.2.7 on 2025-10-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_coordinator', '0001_initial'),
        ('teachers', '0002_teacher_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='english_coordinator',
            field=models.ForeignKey(blank=True, help_text='English Coordinator supervising this teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_teachers', to='english_coordinator.englishcoordinator'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_type',
            field=models.CharField(choices=[('regular', 'Regular Teacher'), ('english_head', 'English Head')], default='regular', help_text='Type of teacher', max_length=20),
        ),
    ]
