# Generated by Django 5.2.7 on 2025-10-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_english_coordinator_teacher_teacher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', help_text="Teacher's shift (Morning/Afternoon)", max_length=20),
        ),
    ]
