# Generated by Django 5.2.7 on 2025-10-17 15:00

from django.db import migrations, models
from django.utils import timezone


def populate_teacher_defaults(apps, schema_editor):
    """Populate default values for existing teacher records"""
    # Skip this for now - just update the schema
    pass


def reverse_populate_teacher_defaults(apps, schema_editor):
    """Reverse migration - no need to do anything"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_old_fields'),
    ]

    operations = [
        # First, make fields nullable temporarily
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, null=True, blank=True, help_text="Teacher's full name"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='father_name',
            field=models.CharField(max_length=200, null=True, blank=True, help_text="Father's name"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=20, null=True, blank=True, unique=True, editable=False, help_text="Auto-generated teacher ID"),
        ),
        
        # Populate default values
        migrations.RunPython(
            populate_teacher_defaults,
            reverse_populate_teacher_defaults,
        ),
        
        # Now make fields non-nullable with defaults
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, default="Unknown Teacher", help_text="Teacher's full name"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='father_name',
            field=models.CharField(max_length=200, default="Unknown", help_text="Father's name"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=20, unique=True, editable=False, default="TEMP-TEACHER-ID", help_text="Auto-generated teacher ID"),
        ),
    ]