# Generated by Django 5.2.7 on 2025-10-17 15:18

from django.db import migrations, models
from django.utils import timezone


def populate_created_at(apps, schema_editor):
    """Populate created_at field for existing records"""
    # Skip data population for now - just update schema
    pass


def reverse_populate_created_at(apps, schema_editor):
    """Reverse migration - no need to do anything"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20251017_1500'),
    ]

    operations = [
        # First, make created_at nullable temporarily
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(null=True, blank=True, auto_now_add=True),
        ),
        
        # Populate existing records
        migrations.RunPython(
            populate_created_at,
            reverse_populate_created_at,
        ),
        
        # Now make created_at non-nullable
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]