# Generated by Django 5.2.7 on 2025-10-17 15:20

from django.db import migrations, models
from django.utils import timezone


def populate_updated_at(apps, schema_editor):
    """Populate updated_at field for existing records"""
    # Skip data population for now - just update schema
    pass


def reverse_populate_updated_at(apps, schema_editor):
    """Reverse migration - no need to do anything"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20251017_1518'),
    ]

    operations = [
        # First, make updated_at nullable temporarily
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(null=True, blank=True, auto_now=True),
        ),
        
        # Populate existing records
        migrations.RunPython(
            populate_updated_at,
            reverse_populate_updated_at,
        ),
        
        # Now make updated_at non-nullable
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]