# Generated by Django 5.2.7 on 2025-10-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0003_add_campus_to_grade'),
        ('teachers', '0006_auto_20251017_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-created_at'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_class',
            field=models.ForeignKey(blank=True, help_text='Class assigned as class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teacher', to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='campus',
            field=models.ForeignKey(help_text='Campus where teacher works', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='campus.campus'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(help_text="Teacher's email address", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is teacher active?'),
        ),
    ]
