# Generated by Django 5.2.7 on 2025-10-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheranalytics',
            name='assigned_grade',
        ),
        migrations.AddField(
            model_name='teacheranalytics',
            name='assigned_class',
            field=models.ForeignKey(blank=True, db_column='assigned_class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.grade'),
        ),
        migrations.AlterField(
            model_name='classanalytics',
            name='grade',
            field=models.ForeignKey(blank=True, db_column='classroom_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='classes.grade'),
        ),
    ]
