# Generated by Django 5.2.7 on 2025-10-21 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='difficulty_score',
            field=models.FloatField(default=1.0, help_text='Detailed difficulty score (1.0-10.0)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='level',
            name='grammar_points',
            field=models.JSONField(blank=True, default=list, help_text='List of grammar points covered in this level'),
        ),
        migrations.AddField(
            model_name='level',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of learning objectives for this level'),
        ),
        migrations.AddField(
            model_name='level',
            name='vocabulary_words',
            field=models.JSONField(blank=True, default=list, help_text='List of vocabulary words taught in this level'),
        ),
        migrations.AddField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='remember', help_text='Cognitive level of this question', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='distractor_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Analysis of why wrong answers are wrong'),
        ),
        migrations.AddField(
            model_name='question',
            name='grammar_tested',
            field=models.CharField(blank=True, help_text='Grammar rule being tested', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='vocabulary_tested',
            field=models.CharField(blank=True, help_text='Vocabulary word being tested', max_length=100),
        ),
    ]
