# Generated by Django 5.2.7 on 2025-10-16 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='group',
            field=models.ForeignKey(default=1, help_text='Group this level belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='groups.group'),
            preserve_default=False,
        ),
    ]
