# Generated by Django 5.2.7 on 2025-10-15 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='levelcompletion',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='levels.level'),
        ),
        migrations.AddField(
            model_name='levelcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(help_text='Level this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='levels.level'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['level_number'], name='levels_leve_level_n_58ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['difficulty'], name='levels_leve_difficu_9cb58a_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['is_active'], name='levels_leve_is_acti_f5fae9_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['is_test_level'], name='levels_leve_is_test_b2da9d_idx'),
        ),
        migrations.AddIndex(
            model_name='levelcompletion',
            index=models.Index(fields=['user', 'level'], name='levels_leve_user_id_218f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='levelcompletion',
            index=models.Index(fields=['completed_at'], name='levels_leve_complet_86c35b_idx'),
        ),
        migrations.AddIndex(
            model_name='levelcompletion',
            index=models.Index(fields=['passed'], name='levels_leve_passed_743c54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='levelcompletion',
            unique_together={('user', 'level')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['level', 'question_order'], name='levels_ques_level_i_963726_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='levels_ques_questio_886e07_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='levels_ques_difficu_367e77_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='levels_ques_is_acti_9f4d9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('level', 'question_order')},
        ),
    ]
