# Generated by Django 5.2.7 on 2025-10-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprogress',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='levelprogress',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='groups.level'),
        ),
        migrations.AddField(
            model_name='levelprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionprogress',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='groups.question'),
        ),
        migrations.AddField(
            model_name='questionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='groupprogress',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='levelprogress',
            unique_together={('user', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='questionprogress',
            unique_together={('user', 'question')},
        ),
    ]
