# Generated by Django 5.2.7 on 2025-10-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(help_text='Campus name', max_length=255)),
                ('campus_code', models.CharField(help_text='Campus code (e.g., C01, C02)', max_length=50, unique=True)),
                ('campus_type', models.CharField(choices=[('main', 'Main'), ('branch', 'Branch')], default='main', max_length=20)),
                ('address', models.TextField(default='Not specified', help_text='Full address')),
                ('city', models.CharField(default='Not specified', help_text='City name', max_length=100)),
                ('phone', models.CharField(default='000-000-0000', help_text='Primary phone number', max_length=20)),
                ('email', models.EmailField(default='campus@example.com', help_text='Official email address', max_length=254)),
                ('head_name', models.CharField(default='Not specified', help_text='Campus head name', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['campus_name'],
                'indexes': [models.Index(fields=['campus_code'], name='campus_camp_campus__06a58e_idx'), models.Index(fields=['city'], name='campus_camp_city_b3fff4_idx'), models.Index(fields=['status'], name='campus_camp_status_dbcb7f_idx')],
            },
        ),
    ]
