# Generated by Django 5.2.7 on 2025-10-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.TextField(blank=True, help_text='Full address', null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='email',
            field=models.EmailField(blank=True, help_text='Official email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='head_name',
            field=models.CharField(blank=True, help_text='Campus head name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary phone number', max_length=20, null=True),
        ),
    ]
