# Generated by Django 5.2.7 on 2025-10-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', help_text='Shift for this grade', max_length=20)),
                ('campus', models.ForeignKey(help_text='Campus this grade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='campus.campus')),
                ('english_teacher', models.ForeignKey(blank=True, help_text='English teacher for this grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='english_teacher_grades', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['name'],
                'unique_together': {('campus', 'name', 'shift')},
            },
        ),
    ]
