# Generated by Django 5.2.7 on 2025-10-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', help_text='Shift for this grade', max_length=20, null=True),
        ),
    ]
