# Generated by Django 5.2.7 on 2025-10-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0003_add_campus_to_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('campus', 'name')},
        ),
        migrations.AlterField(
            model_name='grade',
            name='campus',
            field=models.ForeignKey(help_text='Campus this grade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='campus.campus'),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='level',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
