# Generated by Django 5.2.7 on 2025-10-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='failure_reason',
            field=models.CharField(blank=True, help_text='Reason for login failure', max_length=200, null=True),
        ),
    ]
