# Generated by Django 5.2.7 on 2025-10-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('donor', 'Donor'), ('english_coordinator', 'English Coordinator')], default='admin', max_length=20),
        ),
    ]
