# Generated by Django 5.2.7 on 2025-10-22 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When password was changed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of password change', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('change_type', models.CharField(choices=[('reset', 'Password Reset'), ('change', 'Password Change'), ('admin_reset', 'Admin Reset')], default='change', help_text='Type of password change', max_length=20)),
                ('user', models.ForeignKey(help_text='User who changed password', on_delete=django.db.models.deletion.CASCADE, related_name='password_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Change Log',
                'verbose_name_plural': 'Password Change Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user', 'changed_at'], name='users_passw_user_id_518a6d_idx'), models.Index(fields=['change_type'], name='users_passw_change__fce231_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unique reset token', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When token was created')),
                ('expires_at', models.DateTimeField(help_text='When token expires')),
                ('used', models.BooleanField(default=False, help_text='Whether token has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When token was used', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of reset request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('user', models.ForeignKey(help_text='User requesting password reset', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='users_passw_token_b56ca3_idx'), models.Index(fields=['expires_at'], name='users_passw_expires_853bc2_idx'), models.Index(fields=['used'], name='users_passw_used_5485b2_idx')],
            },
        ),
    ]
