# Generated by Django 5.2.7 on 2025-10-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='User bio', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='is_public_profile',
            field=models.BooleanField(default=False, help_text='Make profile public'),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_style',
            field=models.CharField(blank=True, help_text='Learning style preference', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='native_language',
            field=models.CharField(default='urdu', help_text='Native language', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='target_level',
            field=models.PositiveIntegerField(default=10, help_text='Target level to achieve'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
