# Generated by Django 5.2.7 on 2025-10-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='login_method',
            field=models.CharField(choices=[('student_id', 'Student ID'), ('student_name', 'Student Name'), ('email', 'Email')], help_text='Method used for login', max_length=20),
        ),
    ]
