# Generated by Django 5.2.7 on 2025-10-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordchangelog_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, help_text="Student's campus", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, help_text="Student's grade", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(blank=True, help_text="Student's shift (morning/afternoon)", max_length=20, null=True),
        ),
    ]
