# Generated by Django 5.2.7 on 2025-10-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_campus_user_grade_user_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's name", max_length=200, null=True),
        ),
    ]
