# Generated by Django 5.2.7 on 2025-10-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_loginlog_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='login_method',
            field=models.CharField(choices=[('student_id', 'Student ID'), ('student_name', 'Student Name'), ('student_username', 'Student Username'), ('email', 'Email')], help_text='Method used for login', max_length=20),
        ),
    ]
