# Generated by Django 5.2.7 on 2025-10-22 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0002_alter_campus_address_alter_campus_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervises_all_grades', models.BooleanField(default=True, help_text='Can supervise all grades in campus')),
                ('can_assign_teachers', models.BooleanField(default=True, help_text='Can assign teachers to grades')),
                ('can_view_all_progress', models.BooleanField(default=True, help_text='Can view all student progress')),
                ('can_manage_content', models.BooleanField(default=True, help_text='Can manage English learning content')),
                ('can_reassign_teachers', models.BooleanField(default=True, help_text='Can reassign teachers between grades')),
                ('is_active', models.BooleanField(default=True, help_text='Is coordinator active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(help_text='Campus where English Coordinator works', on_delete=django.db.models.deletion.CASCADE, related_name='english_coordinators', to='campus.campus')),
                ('user', models.OneToOneField(help_text='User account for this English Coordinator', on_delete=django.db.models.deletion.CASCADE, related_name='english_coordinator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'English Coordinator',
                'verbose_name_plural': 'English Coordinators',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campus'], name='english_coo_campus__d890fd_idx'), models.Index(fields=['is_active'], name='english_coo_is_acti_529753_idx')],
                'unique_together': {('user', 'campus')},
            },
        ),
    ]
