# Generated by Django 5.2.7 on 2025-10-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_coordinator', '0001_initial'),
    ]

    operations = [
    ]
