# Generated by Django 5.2.7 on 2025-10-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_alter_campus_address_alter_campus_city_and_more'),
        ('english_coordinator', '0002_auto_20251022_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishcoordinator',
            name='coordinator_id',
            field=models.CharField(default='TEMP-COORDINATOR-ID', editable=False, help_text='Auto-generated coordinator ID', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='englishcoordinator',
            name='email',
            field=models.EmailField(default='temp@coordinator.com', help_text="Coordinator's email address", max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='englishcoordinator',
            name='father_name',
            field=models.CharField(default='Unknown', help_text="Father's name", max_length=200),
        ),
        migrations.AddField(
            model_name='englishcoordinator',
            name='name',
            field=models.CharField(default='Unknown Coordinator', help_text="Coordinator's full name", max_length=200),
        ),
        migrations.AddField(
            model_name='englishcoordinator',
            name='password',
            field=models.CharField(default='password123', help_text="Coordinator's password", max_length=128),
        ),
        migrations.AddField(
            model_name='englishcoordinator',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], default='M', help_text="Coordinator's shift (Morning/Afternoon)", max_length=1),
        ),
        migrations.AlterField(
            model_name='englishcoordinator',
            name='campus',
            field=models.ForeignKey(help_text='Campus where coordinator works', on_delete=django.db.models.deletion.CASCADE, related_name='english_coordinators', to='campus.campus'),
        ),
        migrations.AddIndex(
            model_name='englishcoordinator',
            index=models.Index(fields=['coordinator_id'], name='english_coo_coordin_4dcb6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='englishcoordinator',
            unique_together={('campus', 'shift')},
        ),
    ]
