# Generated by Django 5.2.7 on 2025-10-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_coordinator', '0003_alter_englishcoordinator_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='englishcoordinator',
            name='english_coo_campus__d890fd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='englishcoordinator',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='englishcoordinator',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='englishcoordinator',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='englishcoordinator',
            name='user',
        ),
    ]
