# Generated by Django 5.2.7 on 2025-10-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_coordinator', '0004_remove_englishcoordinator_english_coo_campus__d890fd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishcoordinator',
            name='father_name',
        ),
        migrations.AddField(
            model_name='englishcoordinator',
            name='last_name',
            field=models.CharField(default='Unknown', help_text="Coordinator's last name", max_length=200),
        ),
    ]
