# Generated by Django 5.2.7 on 2025-10-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_coordinator', '0005_remove_englishcoordinator_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishcoordinator',
            name='last_name',
            field=models.CharField(default='Unknown', help_text="Coordinator's last name", max_length=200),
        ),
    ]
